### ISSUE TITLE
Platform crash

### ISSUE THREAD

**Issue by prhuber** [ICICLE-ai/Smartfoodshed_VA_VC1#44]
I loaded the platform, clicked on "Susanville Indian Rancheria", clicked "Retrieve", and got an immediate error:

Error: Request failed with status code 404; Please refresh the page!

Issue Priority: High

**Comment by guzman109** [comment]
Still getting this error.

**Comment by guzman109** [comment]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 156, in read_message
    hi, lo = self.wire.read(2)
  File "/usr/local/lib/python3.8/site-packages/py2neo/wiring.py", line 128, in read
    self.__mark_broken("Network read incomplete "
  File "/usr/local/lib/python3.8/site-packages/py2neo/wiring.py", line 220, in __mark_broken
    raise BrokenWireError(message, idle_time=idle_time,
py2neo.wiring.BrokenWireError: Network read incomplete (received 0 of 2 bytes) after 0.0s idle (7403 bytes sent, 10647 bytes received)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 200, in expand_node_with_relationship_type
    subgraph_res,error_code = helper.graph_after_expand_node(graph,nodes_list,relation_list,expand_node,limit_number,relationship_name,database)
  File "/app/helper.py", line 270, in graph_after_expand_node
    node_list = [graph.nodes.get(i) for i in node_id_list]
  File "/app/helper.py", line 270, in <listcomp>
    node_list = [graph.nodes.get(i) for i in node_id_list]
  File "/usr/local/lib/python3.8/site-packages/py2neo/matching.py", line 619, in get
    return self.match().where("id(_) = %d" % identity).first()
  File "/usr/local/lib/python3.8/site-packages/py2neo/matching.py", line 452, in first
    return self.graph.evaluate(*self._query_and_parameters())
  File "/usr/local/lib/python3.8/site-packages/py2neo/database.py", line 416, in evaluate
    return self.run(cypher, parameters, **kwparameters).evaluate()
  File "/usr/local/lib/python3.8/site-packages/py2neo/database.py", line 405, in run
    return self.auto().run(cypher, parameters, **kwparameters)
  File "/usr/local/lib/python3.8/site-packages/py2neo/database.py", line 992, in run
    self._connector.pull(result, -1)
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 1434, in pull
    cx.pull(result, n=n)
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 995, in pull
    self._sync(response)
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 799, in _sync
    self._wait(response)
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 794, in _wait
    self._fetch()
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 769, in _fetch
    tag, fields = self.read_message()
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 696, in read_message
    tag, fields = self._reader.read_message()
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 158, in read_message
    raise_from(ConnectionBroken("Failed to read message"), error)
  File "<string>", line 3, in raise_from
py2neo.errors.ConnectionBroken: Failed to read message
`

**Comment by yasmineTYM** [comment]
https://github.com/py2neo-org/py2neo/issues/844

I found sometimes we ran into this problem but it is hard to debug as it is an internal error from Py2neo. Also, there is actually no issue in the connection of Neo4j. I just add a few more attempts for calling this function. Hopefully it will solve this error. Please let me know if you ran into this problem again.

**Comment by yasmineTYM** [comment]
10.244.4.48 - - [26/Jun/2023 13:10:08] "OPTIONS /retrieveSubgraph HTTP/1.1" 200 -
404 - Failed to read message
10.244.4.48 - - [26/Jun/2023 13:10:08] "POST /retrieveSubgraphWithR HTTP/1.1" 404 -
200
